### ISSUE TITLE
Tests failing for 0.2.0

### ISSUE THREAD

**Issue by grawlinson** [chasinglogic/licensure#17]
A test has started failing in `0.2.0`, were previously passing in `0.1.3`.

```sh
$ RUST_BACKTRACE=1 cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.11s
     Running unittests (target/debug/deps/licensure-5ae8895cc79d2b20)

running 11 tests
test comments::tests::test_comment_cpp ... ok
test comments::tests::test_comment_html ... ok
test comments::tests::test_comment_python ... ok
test comments::tests::test_comment_cpp_w_trailing_lines ... ok
test comments::tests::test_comment_python_w_trailing_lines ... ok
test config::comment::tests::test_get_filetype ... ok
test template::tests::test_substitutions ... ok
test template::tests::test_substitution_at_end_of_line ... ok
test template::tests::test_substitutions_prewrapped ... ok
test template::tests::test_substitutions_prewrapped_preserves_linebreaks ... ok
test test::test_get_project_files ... FAILED

failures:

---- test::test_get_project_files stdout ----
thread 'test::test_get_project_files' panicked at 'assertion failed: get_project_files().len() != 0', src/main.rs:207:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.57.0/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/1.57.0/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/1.57.0/library/core/src/panicking.rs:50:5
   3: licensure::test::test_get_project_files
             at ./src/main.rs:207:9
   4: licensure::test::test_get_project_files::{{closure}}
             at ./src/main.rs:206:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/1.57.0/library/core/src/ops/function.rs:227:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/1.57.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test::test_get_project_files

test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s
```

**Comment by grawlinson** [comment]
Tests seem to be passing in `0.2.1`, so I'm going to go ahead and close this issue.
